# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MinkowskiReduction]]
deps = ["LinearAlgebra", "Random"]
git-tree-sha1 = "b66b9bbcc6292ac9b8eab088ee05cb4326f3aef1"
repo-rev = "main"
repo-url = "https://github.com/glwhart/MinkowskiReduction.jl"
uuid = "d617d09d-b3c0-43f1-8886-30d89b900f25"
version = "0.1.0"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
