name = "Pointy"
uuid = "8a99ab59-17de-42fd-a8e5-4c52ccbc678b"
authors = ["Gus Hart"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MinkowskiReduction = "d617d09d-b3c0-43f1-8886-30d89b900f25"

[compat]
BenchmarkTools = "0.7"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
